services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./timezone:/etc/timezone:ro
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-home-baby
    environment:
      POSTGRES_DB: home-baby
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Senai@127
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  postgres-data:
  logs:
  timezone:
