package com.homebaby.enums;

import lombok.Getter;

@Getter
public enum IncomeType {
    ONE_THOUSAND_TO_TWO_THOUSAND("ONE_THOUSAND_TO_TWO_THOUSAND"),
    TWO_THOUSAND_AND_ONE_TO_THREE_THOUSAND("TWO_THOUSAND_AND_ONE_TO_THREE_THOUSAND"),
    THREE_THOUSAND_AND_ONE_TO_FIVE_THOUSAND("THREE_THOUSAND_AND_ONE_TO_FIVE_THOUSAND"),
    FIVE_THOUSAND_AND_ONE_TO_EIGHT_THOUSAND("FIVE_THOUSAND_AND_ONE_TO_EIGHT_THOUSAND"),
    EIGHT_THOUSAND_AND_ONE_TO_TWELVE_THOUSAND("EIGHT_THOUSAND_AND_ONE_TO_TWELVE_THOUSAND"),
    TWELVE_THOUSAND_TO_MORE("TWELVE_THOUSAND_TO_MORE");

    private final String incomeType;

    IncomeType(String incomeType) {
        this.incomeType = incomeType;
    }
}
